spring.application.name=EmployeeManagement
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management
spring.datasource.username=root
spring.datasource.password=Rajesh@1234

jwt.secret=TXlQYXlyb2xsU2VjdXJlS2V5Rm9yRGV2ZWxvcG1lbnRPbmx5MTIzNDU2Nzg5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

